# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-03 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20170103_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
