# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-03 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_remove_catagory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
